### ISSUE TITLE
fatal error: boost_multiprecision_number_compare_bug_workaround.hpp: No such file or directory

### ISSUE THREAD

**Issue by chenshuijin** [comaeio/porosity#54]
# fatal error: boost_multiprecision_number_compare_bug_workaround.hpp: No such file or directory

I build on Ubuntu 5.4.0-6ubuntu1~16.04.9. And got an error:
```
/home/ubuntu/git/porosity/porosity/porosity/Common.h:48:66: fatal error: boost_multiprecision_number_compare_bug_workaround.hpp: No such file or directory
compilation terminated.
CMakeFiles/porosity.dir/build.make:62: recipe for target 'CMakeFiles/porosity.dir/Debug.cpp.o' failed
make[2]: *** [CMakeFiles/porosity.dir/Debug.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/porosity.dir/all' failed
make[1]: *** [CMakeFiles/porosity.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
My steps to build:
- `cd /home/ubuntu/git/porosity/porosity/porosity/ && cmake . `
- `make`
