### ISSUE TITLE
Changes for compiling on macOS

### ISSUE THREAD

**Issue by beaugunderson** [comaeio/porosity#4]
I had to add this to `Makefile` to get it to work:

```sh
CXX=g++  # or c++, clang works too
CXXFLAGS=-std=c++14
```

I also had to inline `assertThrow` from `Assert.h` into `Instruction.h` because the compiler complained that it wasn't defined--my C++ knowledge is limited so I don't have a guess as to why.

**Comment by vors** [comment]
That would make a good pool request :)

**Comment by msuiche** [comment]
Yes, pull request please :)

**Comment by beaugunderson** [comment]
OK, PR #6 for the Makefile change but I don't know how to fix the issue with `assertThrow` other than moving the definition to `Instruction.h`, which seems wrong. :)

For what it's worth here's the compiler error:

```
In file included from Contract.cpp:18:
In file included from ./Porosity.h:41:
In file included from ./PorosityDefs.h:20:
./Instruction.h:214:56: error: use of undeclared identifier 'InvalidOpcode'
            assertThrow(1 <= _number && _number <= 32, InvalidOpcode, "Invalid PUSH instruction requested.");
```

I changed `InvalidOpcode` to a string when I was initially investigating; that results in this error:

```
In file included from Contract.cpp:18:
In file included from ./Porosity.h:41:
In file included from ./PorosityDefs.h:20:
./Instruction.h:214:13: error: use of undeclared identifier 'assertThrow'
            assertThrow(1 <= _number && _number <= 32, "InvalidOpcode", "Invalid PUSH instruction requested.");
```

**Comment by reiven** [comment]
Also it will be great to make it available for linux

**Comment by kthomas** [comment]
@reiven I was able to get things to compile on linux using this branch (check out newest 2 commits): https://github.com/kthomas/porosity/commits/linux-make

It worked on Ubuntu 16.04.2 with `BOOST_VERSION 105800`.

**Comment by beaugunderson** [comment]
@conor10 can you put the ABI and code in your comment (or a gist) as a bash script so I can easily run it?

**Comment by conor10** [comment]
https://raw.githubusercontent.com/web3j/web3j/master/src/test/resources/solidity/greeter/build/greeter.abi
https://raw.githubusercontent.com/web3j/web3j/master/src/test/resources/solidity/greeter/build/greeter.bin
https://raw.githubusercontent.com/web3j/web3j/master/src/test/resources/solidity/greeter/Greeter.sol

Build script as per https://github.com/web3j/web3j/blob/master/src/test/resources/solidity/build.sh

**Comment by beaugunderson** [comment]
@conor10 sorry, I wanted something to copy and paste :) willing to help but limited time

**Comment by msuiche** [comment]
@beaugunderson can you confirm the macOS compilation issue had been fixed with the recent pull request ?

**Comment by genecyber** [comment]
> @beaugunderson can you confirm the macOS compilation issue had been fixed with the recent pull request ?

I added PR #16 to finish the fix for OSX

I'll add a new PR with doc cleanup and OSX build instructions
